name: Tests
on: [push, pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test
