name: Tests
on: [push, pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test
